---
title: "Keyword_check"
author: "Roberto Lentini"
date: "03/06/2021"
output: html_document
---
```{r}
# imports
library(tidyverse)
library(tidytext)
library(tidyverse)
library(pluralize)
library(naniar)
library(data.table)
library(purrr)
```

```{r}
data <- read.csv('C:/document_similarity_checker/ONDRISubmissionPortalFullList .csv')
colnames(data)
colnames(data) <- c('id','author', 'title', 'text')
corpus_raw <- data %>% select('id', 'author', 'title', 'text')
head(corpus_raw)
```

```{r}
# seperating input into list of words
input <- "ONDRI Neuropsychology Platform, Gait variability, Intraindividual, While FTD has been"
input_word_list <- as.list(strsplit(input, ","))

for (word in input_word_list[[1]]) {
  word <- trimws(word, which = "both")
  found <- sapply(word, grepl, corpus_raw$text)
  corpus_raw <- cbind(corpus_raw,found)
}

# counting the amount of common keywords found in each proposal
corpus_clean <- subset(corpus_raw, select = -c(id, text, title, author) )
amount_of_commonWords <- apply(corpus_clean,MARGIN=1,table)
corpus_raw$amount_of_commonWords <- amount_of_commonWords
corpus_raw <- corpus_raw %>% unnest_auto(amount_of_commonWords) %>% unnest(cols = c(`FALSE`, `TRUE`))
corpus_raw[is.na(corpus_raw)] <- 0
# (colnames(corpus_raw))[corpus_raw[length(corpus_raw)]] <- "newname2"
colnames(corpus_raw)[length(corpus_raw)] <- 'amount_of_wordsCommon'
# corpus_raw$TRUE <- as.numeric(as.character(corpus_raw$TRUE))
results <- corpus_raw[order(corpus_raw$amount_of_wordsCommon, decreasing = TRUE),]
final_results <- results %>%
  top_n(5)
##Go through each row and determine if a value is zero
row_sub = apply(final_results, 1, function(row) all(row !=0 ))
##Subset as usual
final_results <- final_results[row_sub,]

# TODO: Optimize this
common_words <- c()
for (row in final_results$text) {
  str_commonWords <- ''
  for (word in input_word_list[[1]]) {
    word <- trimws(word, which = "both")
    if (grepl(word, row, fixed = TRUE)) {
      str_commonWords <- paste(str_commonWords, word, sep = ",")
    }
  }
  common_words <- c(common_words, str_commonWords)
}

final_results$common_words <- common_words
```










